src/FabioCosta.Web/Controllers/NewsletterController.cs
namespace FabioCosta.Web.Controllers;

using FabioCosta.Web.Constants;

using Microsoft.AspNetCore.Mvc;

[Route("/newsletter")]
public class NewsletterController : Controller
{
    [Route("")]
    [ResponseCache(CacheProfileName = CacheConstants.Weekly)]
    public IActionResult Index()
    {
        return View();
    }
}

src/FabioCosta.Web/Controllers/PrivacyController.cs
namespace FabioCosta.Web.Controllers;

using FabioCosta.Web.Constants;

using Microsoft.AspNetCore.Mvc;

[Route("/privacy")]
public class PrivacyController : Controller
{
    [Route("")]
    [ResponseCache(CacheProfileName = CacheConstants.Weekly)]
    public IActionResult Index()
    {
        return View();
    }
}

src/FabioCosta.Web/Controllers/SiteMapController.cs
namespace FabioCosta.Web.Controllers;

using FabioCosta.Web.Constants;
using FabioCosta.Web.Interfaces;

using Microsoft.AspNetCore.Mvc;

using SimpleMvcSitemap;

using System.Collections.Generic;
using System.Threading.Tasks;

[Route("/")]
public class SiteMapController : Controller
{
    private readonly ISitemapProvider _sitemapProvider;
    private readonly IBlogService _blogService;

    public SiteMapController(ISitemapProvider sitemapProvider, IBlogService blogService)
    {
        _sitemapProvider = sitemapProvider;
        _blogService = blogService;
    }

    [Route("SiteMap.xml")]
    [ResponseCache(CacheProfileName = CacheConstants.Daily)]
    public async Task<IActionResult> Index()
    {
        const string indexString = "Index";
        string scheme = HttpContext.Request.Scheme == "http" ? $"{HttpContext.Request.Scheme}s" : HttpContext.Request.Scheme;

        var nodes = new List<SitemapNode>
            {
                new (Url.Action(indexString,"Home", null, scheme))
                {
                    ChangeFrequency = ChangeFrequency.Weekly,
                    Priority = 1.0M
                },
                new (Url.Action(indexString,"Privacy", null, scheme))
                {
                    ChangeFrequency = ChangeFrequency.Yearly,
                    Priority = 0.3M
                },
                new (Url.Action(indexString, "Blog", null, scheme))
                {
                    ChangeFrequency = ChangeFrequency.Daily,
                    Priority = 0.8M
                }
            };

        // Blog posts
        var posts = await _blogService.GetBlogPostsByPageSlugAsync("blog");
        foreach (var post in posts.Archive.Posts)
        {
            var node = new SitemapNode(Url.Action("Post", "Blog", new { slug = post.Slug }, scheme))
            {
                ChangeFrequency = ChangeFrequency.Weekly,
                Priority = 1.0M
            };

            nodes.Add(node);
        }

        return _sitemapProvider.CreateSitemap(new SitemapModel(nodes));
    }
}

src/FabioCosta.Web/ViewComponents/CookieConsentViewComponent.cs
namespace FabioCosta.Web.ViewComponents;

using FabioCosta.Web.Constants;
using FabioCosta.Web.Models;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;

public class CookieConsentViewComponent : ViewComponent
{
    [ResponseCache(CacheProfileName = CacheConstants.NoCache)]
    public IViewComponentResult Invoke()
    {
        var consentFeature = HttpContext.Features.Get<ITrackingConsentFeature>();
        CookieConsentModel cookieConsentModel = new()
        {
            ShowBanner = !consentFeature?.CanTrack ?? false,
            CookieString = consentFeature?.CreateConsentCookie()
        };

        return View(cookieConsentModel);
    }
}

src/FabioCosta.Web/Views/Shared/_BackTopButton.cshtml
<!-- Back to top button -->
<a id="backTopButton"></a>

src/FabioCosta.Web/Views/Shared/_Footer.cshtml
@using FabioCosta.Web.Helper;

<footer class="site-footer safari_only">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <p class="copyright-text">
                    Copyright &copy; @DateTime.Now.Year <a title="Home" asp-controller="Home" asp-action="Index">Fábio Costa</a>
                    <span> | </span>
                    <a title="Source code" href="https://github.com/fabiocosta89/fabiocosta" target="_blank" rel="noreferrer">Source code</a>
                </p>
                <ul class="footer-link">
                    <li>@AssemblyHelper.GetAppVersionWithBuild()</li>
                    <li><a asp-controller="Privacy" asp-action="Index">Privacy</a></li>
                    <li><a title="Feed RSS" href="https://feeds.feedburner.com/fabiocosta/Pleahq1obG2">Feed RSS</a></li>
                    <li><a asp-controller="SiteMap" asp-action="Index">SiteMap</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

src/FabioCosta.Web/Views/Shared/_Head.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<!-- Primary Meta Tags -->
<title>@ViewData["Title"] - Fabio Costa</title>
<meta name="title" content="@ViewData["Title"] - Fabio Costa">
<meta name="description" content="@ViewData["Description"]">
<meta name="author" content="Fabio Costa">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://fabiocosta.eu/">
<meta property="og:title" content="@ViewData["Title"] - Fabio Costa">
<meta property="og:description" content="@ViewData["Description"]">
<meta property="og:image" content='@(ViewData["Image"] ?? $"{Context.Request.Scheme}://{Context.Request.Host}/images/shared/profile-pic.png")'>

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://fabiocosta.eu/">
<meta property="twitter:title" content="@ViewData["Title"] - Fabio Costa">
<meta property="twitter:description" content="@ViewData["Description"]">
<meta property="twitter:image" content='@(ViewData["Image"] ?? $"{Context.Request.Scheme}://{Context.Request.Host}/images/shared/profile-pic.png")'>

<link rel="canonical" href="https://@Context.Request.Host@Context.Request.Path">
<meta name="theme-color" content="#4191EB">
<meta name="robots" content="index, follow">

<!-- Favicon -->
<link rel="apple-touch-icon-precomposed" sizes="57x57" href="/favicon/apple-touch-icon-57x57.png" >
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/favicon/apple-touch-icon-114x114.png" >
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/favicon/apple-touch-icon-72x72.png" >
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/favicon/apple-touch-icon-144x144.png" >
<link rel="apple-touch-icon-precomposed" sizes="60x60" href="/favicon/apple-touch-icon-60x60.png" >
<link rel="apple-touch-icon-precomposed" sizes="120x120" href="/favicon/apple-touch-icon-120x120.png" >
<link rel="apple-touch-icon-precomposed" sizes="76x76" href="/favicon/apple-touch-icon-76x76.png" >
<link rel="apple-touch-icon-precomposed" sizes="152x152" href="/favicon/apple-touch-icon-152x152.png" >
<link rel="icon" type="image/png" href="/favicon/favicon-196x196.png" sizes="196x196" >
<link rel="icon" type="image/png" href="/favicon/favicon-96x96.png" sizes="96x96" >
<link rel="icon" type="image/png" href="/favicon/favicon-32x32.png" sizes="32x32" >
<link rel="icon" type="image/png" href="/favicon/favicon-16x16.png" sizes="16x16" >
<link rel="icon" type="image/png" href="/favicon/favicon-128.png" sizes="128x128" >
<meta name="application-name" content="&nbsp;" >
<meta name="msapplication-TileColor" content="#FFFFFF" />
<meta name="msapplication-TileImage" content="/favicon/mstile-144x144.png" >
<meta name="msapplication-square70x70logo" content="/favicon/mstile-70x70.png" >
<meta name="msapplication-square150x150logo" content="/favicon/mstile-150x150.png" >
<meta name="msapplication-wide310x150logo" content="/favicon/mstile-310x150.png" >
<meta name="msapplication-square310x310logo" content="/favicon/mstile-310x310.png" >

<!-- Libraries -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous" />
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" integrity="sha384-/rJKQnzOkEo+daG0jMjU1IwwY9unxt1NBw3Ef2fmOJ3PW/TfAg2KXVoWwMZQZtw9" crossorigin="anonymous" />
<!-- Fonts -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/fontawesome.min.css" rel="stylesheet" integrity="sha384-wESLQ85D6gbsF459vf1CiZ2+rr+CsxRY0RpiF1tLlQpDnAgg6rwdsUF1+Ics2bni" crossorigin="anonymous" referrerpolicy="no-referrer" font-display="swap" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/brands.min.css" rel="stylesheet" integrity="sha384-V5Z1KgRRJyY878qCx7+zUeTDm0FgjoYrbmSortFqRPGz+Ue6XDe4uIiMqB3tB/wd" crossorigin="anonymous" referrerpolicy="no-referrer" font-display="swap" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/solid.min.css" rel="stylesheet" integrity="sha384-LA8Ug4T/nhVkyhrSmSirsoAo9iDrBk8E7U80aSPeD+w3vO8PzOJIS6agGcbIwwX0" crossorigin="anonymous" referrerpolicy="no-referrer" font-display="swap" />
<!-- MAIN CSS -->
<link rel="stylesheet" href="/css/bundle.css" asp-append-version="true" />

<!-- Umami -->
<script async defer data-website-id="@Configuration["Umami:Id"]" src="@Configuration["Umami:Url"]"></script>

src/FabioCosta.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <partial name="_Head" />
    <!-- Page Specific -->
    @await RenderSectionAsync("Head", required: false)
</head>
<body>
    <div id="page-container">
        <main id="content-wrap">
            <!-- Back to Top Button -->
            <partial name="_BackTopButton" />

            <!-- MENU BAR -->
            <partial name="_Menu" />

            @RenderBody()
        </main>

        <!-- Footer -->
        <partial name="_Footer" />

        <!-- Cookie consent -->
        @*<partial name="_CookieConsentPartial" />*@
        @await Component.InvokeAsync("CookieConsent")
    </div>

    <!-- SCRIPTS -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script>
    <script async src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js" integrity="sha384-wziAfh6b/qT+3LrqebF9WeK4+J5sehS6FA10J1t3a866kJ/fvU5UwofWnQyzLtwu" crossorigin="anonymous"></script>
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/smoothscroll/1.4.10/SmoothScroll.min.js" integrity="sha384-vkQNjF8EA4RcQjAxDIUub2eNccKwbbUVUxouY1MuGjSfXCl4mfsstaL6+AZsfuhD" crossorigin="anonymous"></script>
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/rellax/1.12.1/rellax.min.js" integrity="sha384-pSQdnqsuAwdyk3FjmdCugWc6JXrpCyQPJbweAfCT9EjnJayrGAKKuI6V54wCfQ5c" crossorigin="anonymous"></script>
    <script async src="~/js/CookieConsent.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/FabioCosta.Web/Views/Shared/_Menu.cshtml
<nav id="navbar" class="navbar navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">
            <img src="~/images/shared/fc_white.svg" 
                 alt="Fábio Costa logo" 
                 class="nav-logo" 
                 rel="preload" 
                 width="32"
                 height="32">
            <span>Fábio Costa</span>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="/blog" class="nav-link nav-text">Blog</a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Newsletter" asp-action="Index" class="nav-link nav-text">Newsletter</a>
                </li>
                <li class="nav-item">
                    <a title="LinkedIn" href="https://www.linkedin.com/in/fabio-o-costa" class="fab fa-linkedin nav-link" target="_blank" rel="noreferrer"></a>
                    <a title="Github" href="https://github.com/fabiocosta89" class="fab fa-github nav-link" target="_blank" rel="noreferrer"></a>
                    <a title="Email" href="mailto: me@fabiocosta.eu" class="fa fa-envelope nav-link" target="_blank" rel="noreferrer"></a>
                </li>
            </ul>
        </div>
    </div>
</nav>

src/FabioCosta.Web/Views/Shared/_pagination.cshtml
@model PostArchive<PostInfo>

@{
    bool hasPrevious = Model.CurrentPage != 1;
    bool hasNext = Model.CurrentPage != Model.TotalPages;
}

@if (Model.TotalPages != 1)
{
    <nav aria-label="pagination" data-aos="fade-up">
        <ul class="pagination justify-content-center">
            <li class='page-item @(!hasPrevious ? "disabled" : "")'>
                @if (hasPrevious)
                {
                    <a class="page-link" href="/blog/page/@(Model.CurrentPage-1)">Previous</a>
                }
                else 
                {
                    <span class="page-link">Previous</span>
                }
            </li>
            @if (Model.CurrentPage - 1 > 1)
            {
                <li class="page-item">
                    <a class="page-link" href="/blog/page/1">1</a>
                </li>
            }
            @if (Model.CurrentPage - 1 > 2)
            {
                <li class="page-item">
                    <span class="page-link">
                        ...
                    </span>
                </li>
            }
            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" href="/blog/page/@(Model.CurrentPage-1)">@(Model.CurrentPage-1)</a>
                </li>
            }
            <li class="page-item active">
                <span class="page-link">
                    @Model.CurrentPage
                    <span class="sr-only">(current)</span>
                </span>
            </li>
            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" href="/blog/page/@(Model.CurrentPage+1)">@(Model.CurrentPage + 1)</a>
                </li>
            }
            @if (Model.CurrentPage + 1 < Model.TotalPages - 1)
            {
                <li class="page-item">
                    <span class="page-link">
                        ...
                    </span>
                </li>
            }
            @if (Model.CurrentPage + 1 < Model.TotalPages )
            {
                <li class="page-item">
                    <a class="page-link" href="/blog/page/@(Model.TotalPages)">@Model.TotalPages</a>
                </li>
            }
            <li class='page-item @(!hasNext ? "disabled" : "")'>
                @if (hasNext)
                {
                    <a class="page-link" href="/blog/page/@(Model.CurrentPage+1)">Next</a>
                }
                else
                {
                    <span class="page-link">Next</span>
                }
            </li>
        </ul>
    </nav>
}